version: '3.3'

services:
  # nginx:
  #   container_name: traffic-commander-nginx
  #   image: notadevteam/traffic-commander-nginx
  #   build:
  #     context: ./
  #     dockerfile: ./dockerfiles/nginx.Dockerfile
  #   ports:
  #     - 80:80
  #   depends_on:
  #     - fluentd

  fluentd:
    container_name: traffic-commander-fluentd
    image: notadevteam/traffic-commander-fluentd
    build:
      context: ./
      dockerfile: ./dockerfiles/fluentd.Dockerfile
    ports:
      - 8888:8888
      - 8888:8888/udp
    volumes:
      - ./fluentd/conf:/fluentd/etc
      - ./fluentd/log:/fluentd/log

  elastic:
    container_name: traffic-commander-elastic
    image: notadevteam/traffic-commander-elastic
    build:
      context: ./
      dockerfile: ./dockerfiles/elastic.Dockerfile
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - ./elastic/data:/usr/share/elasticsearch/data
    depends_on:
      - fluentd

  kibana:
    container_name: traffic-commander-kibana
    image: notadevteam/traffic-commander-kibana
    build:
      context: ./
      dockerfile: ./dockerfiles/kibana.Dockerfile
    ports:
      - 5601:5601
    depends_on:
      - elastic
